
name: Build Loop via Fastlane

on:
  push:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true
        working-directory: fastlane

    - name: Setup project team
      working-directory: fastlane
      run: bundle exec fastlane update_project_team

    - name: Run Fastlane Build
      working-directory: fastlane
      env:
        FASTLANE_KEY_ID: ${{ secrets.FASTLANE_KEY_ID }}
        FASTLANE_ISSUER_ID: ${{ secrets.FASTLANE_ISSUER_ID }}
      run: bundle exec fastlane build
