
name: Build Loop

on:
  workflow_dispatch:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout LoopWorkspace
        uses: actions/checkout@v4
        with:
          repository: 'LoopKit/LoopWorkspace'
          token: ${{ secrets.GH_PAT }}
          submodules: 'recursive'
          path: 'Loop'

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.4.0'

      - name: Prepare Workspace and Build
        run: |
          cd Loop
          echo "Führe Workspace-Vorbereitung aus..."
          ./Scripts/manual_LoopWorkspace_prepare_pr.sh
          
          echo "Patching project signing settings..."
          find . -name "project.pbxproj" -exec sed -i '' 's/CODE_SIGN_STYLE = Automatic;/CODE_SIGN_STYLE = Manual;/g' {} +
          
          echo "Starte Build..."
          xcodebuild -workspace LoopWorkspace.xcworkspace -scheme Loop -destination 'generic/platform=iOS Simulator' CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" build
